/**
 * Protocol Definitions Index (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * Imports all protocol definitions and registers them at import time.
 * This ensures the protocol registry is populated when the Next.js
 * server starts (via the plugin import chain).
 *
 * Registered protocols: aave, aerodrome, ajna, chainlink, compound, cowswap, curve, ethena, lido, morpho, pendle, rocket-pool, safe, sky, spark, uniswap, weth, yearn
 */

import { protocolToPlugin, registerProtocol } from "@/lib/protocol-registry";
import { registerIntegration } from "@/plugins/registry";

import aaveDef from "./aave-v3";
import aerodromeDef from "./aerodrome";
import ajnaDef from "./ajna";
import chainlinkDef from "./chainlink";
import compoundDef from "./compound-v3";
import cowswapDef from "./cowswap";
import curveDef from "./curve";
import ethenaDef from "./ethena";
import lidoDef from "./lido";
import morphoDef from "./morpho";
import pendleDef from "./pendle";
import rocketPoolDef from "./rocket-pool";
import safeDef from "./safe";
import skyDef from "./sky";
import sparkDef from "./spark";
import uniswapDef from "./uniswap-v3";
import wethDef from "./weth";
import yearnDef from "./yearn-v3";

registerProtocol(aaveDef);
registerIntegration(protocolToPlugin(aaveDef));
registerProtocol(aerodromeDef);
registerIntegration(protocolToPlugin(aerodromeDef));
registerProtocol(ajnaDef);
registerIntegration(protocolToPlugin(ajnaDef));
registerProtocol(chainlinkDef);
registerIntegration(protocolToPlugin(chainlinkDef));
registerProtocol(compoundDef);
registerIntegration(protocolToPlugin(compoundDef));
registerProtocol(cowswapDef);
registerIntegration(protocolToPlugin(cowswapDef));
registerProtocol(curveDef);
registerIntegration(protocolToPlugin(curveDef));
registerProtocol(ethenaDef);
registerIntegration(protocolToPlugin(ethenaDef));
registerProtocol(lidoDef);
registerIntegration(protocolToPlugin(lidoDef));
registerProtocol(morphoDef);
registerIntegration(protocolToPlugin(morphoDef));
registerProtocol(pendleDef);
registerIntegration(protocolToPlugin(pendleDef));
registerProtocol(rocketPoolDef);
registerIntegration(protocolToPlugin(rocketPoolDef));
registerProtocol(safeDef);
registerIntegration(protocolToPlugin(safeDef));
registerProtocol(skyDef);
registerIntegration(protocolToPlugin(skyDef));
registerProtocol(sparkDef);
registerIntegration(protocolToPlugin(sparkDef));
registerProtocol(uniswapDef);
registerIntegration(protocolToPlugin(uniswapDef));
registerProtocol(wethDef);
registerIntegration(protocolToPlugin(wethDef));
registerProtocol(yearnDef);
registerIntegration(protocolToPlugin(yearnDef));
