/**
 * KeeperHub Plugins Index (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * KeeperHub-specific plugins that extend the base workflow builder.
 * These plugins are loaded in addition to the base plugins.
 *
 * Discovered plugins: code, discord, math, protocol, safe, sendgrid, telegram, web3, webhook
 */

import "./code";
import "./discord";
import "./math";
import "./protocol";
import "./safe";
import "./sendgrid";
import "./telegram";
import "./web3";
import "./webhook";
