export default {
  kh: "kh",
  kh_action: "kh action",
  kh_action_get: "kh action get",
  kh_action_list: "kh action list",
  kh_auth: "kh auth",
  kh_auth_login: "kh auth login",
  kh_auth_logout: "kh auth logout",
  kh_auth_status: "kh auth status",
  kh_billing: "kh billing",
  kh_billing_status: "kh billing status",
  kh_billing_usage: "kh billing usage",
  kh_completion: "kh completion",
  kh_config: "kh config",
  kh_config_get: "kh config get",
  kh_config_list: "kh config list",
  kh_config_set: "kh config set",
  kh_doctor: "kh doctor",
  kh_execute: "kh execute",
  "kh_execute_contract-call": "kh execute contract-call",
  kh_execute_status: "kh execute status",
  kh_execute_transfer: "kh execute transfer",
  kh_org: "kh org",
  kh_org_list: "kh org list",
  kh_org_members: "kh org members",
  kh_org_switch: "kh org switch",
  kh_project: "kh project",
  kh_project_create: "kh project create",
  kh_project_delete: "kh project delete",
  kh_project_get: "kh project get",
  kh_project_list: "kh project list",
  kh_protocol: "kh protocol",
  kh_protocol_get: "kh protocol get",
  kh_protocol_list: "kh protocol list",
  kh_run: "kh run",
  kh_run_cancel: "kh run cancel",
  kh_run_logs: "kh run logs",
  kh_run_status: "kh run status",
  kh_serve: "kh serve",
  kh_tag: "kh tag",
  kh_tag_create: "kh tag create",
  kh_tag_delete: "kh tag delete",
  kh_tag_get: "kh tag get",
  kh_tag_list: "kh tag list",
  kh_template: "kh template",
  kh_template_deploy: "kh template deploy",
  kh_template_list: "kh template list",
  kh_update: "kh update",
  kh_version: "kh version",
  kh_wallet: "kh wallet",
  kh_wallet_balance: "kh wallet balance",
  kh_wallet_tokens: "kh wallet tokens",
  kh_workflow: "kh workflow",
  kh_workflow_get: "kh workflow get",
  "kh_workflow_go-live": "kh workflow go-live",
  kh_workflow_list: "kh workflow list",
  kh_workflow_pause: "kh workflow pause",
  kh_workflow_run: "kh workflow run",
};
