/**
 * Integration Types (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * To add a new integration type:
 * 1. Create a plugin in plugins/ or plugins/ directory, OR
 * 2. Add a system integration to SYSTEM_INTEGRATION_TYPES in discover-plugins.ts
 * 3. Run: pnpm discover-plugins
 *
 * Generated types: aave, aerodrome, ai-gateway, ajna, chainlink, chronicle, clerk, code, compound, cowswap, curve, database, discord, ethena, lido, linear, math, morpho, pendle, protocol, resend, rocket-pool, safe, sendgrid, sky, slack, spark, telegram, uniswap, v0, web3, webflow, webhook, wrapped, yearn
 */

// Integration type union - plugins + system integrations
export type IntegrationType =
  | "aave"
  | "aerodrome"
  | "ai-gateway"
  | "ajna"
  | "chainlink"
  | "chronicle"
  | "clerk"
  | "code"
  | "compound"
  | "cowswap"
  | "curve"
  | "database"
  | "discord"
  | "ethena"
  | "lido"
  | "linear"
  | "math"
  | "morpho"
  | "pendle"
  | "protocol"
  | "resend"
  | "rocket-pool"
  | "safe"
  | "sendgrid"
  | "sky"
  | "slack"
  | "spark"
  | "telegram"
  | "uniswap"
  | "v0"
  | "web3"
  | "webflow"
  | "webhook"
  | "wrapped"
  | "yearn";

// Generic config type - plugins define their own keys via formFields[].configKey
export type IntegrationConfig = Record<string, string | boolean | undefined>;
