export default {
  overview: "Overview",
  web3: "Web3",
  code: "Code",
  math: "Math",
  safe: "Safe",
  "safe-wallet": "Safe Wallet",
  ajna: "Ajna",
  pendle: "Pendle",
  sky: "Sky",
  discord: "Discord",
  telegram: "Telegram",
  sendgrid: "SendGrid",
  webhook: "Webhook",
};
