export default {
  overview: "Overview",
  web3: "Web3",
  code: "Code",
  math: "Math",
  safe: "Safe",
  "aave-v3": "Aave V3",
  ajna: "Ajna",
  compound: "Compound V3",
  cowswap: "CoW Swap",
  curve: "Curve",
  lido: "Lido",
  morpho: "Morpho",
  pendle: "Pendle",
  "rocket-pool": "Rocket Pool",
  sky: "Sky",
  spark: "Spark",
  uniswap: "Uniswap",
  discord: "Discord",
  telegram: "Telegram",
  sendgrid: "SendGrid",
  webhook: "Webhook",
};
