/**
 * Protocol Plugin Shell
 *
 * Protocol integrations are dynamically generated from protocol definitions
 * in protocols/. Each protocol becomes its own IntegrationPlugin
 * via protocolToPlugin() in lib/protocol-registry.ts.
 *
 * The import below triggers protocol registration at server startup:
 * protocols/index.ts is auto-generated by discover-plugins and
 * calls registerProtocol() + registerIntegration() for each protocol definition.
 */

// Register all protocol definitions at import time (auto-generated barrel)
import "@/protocols";
