/**
 * Protocol Definitions Index (Auto-Generated)
 *
 * This file is automatically generated by scripts/discover-plugins.ts
 * DO NOT EDIT MANUALLY - your changes will be overwritten!
 *
 * Imports all protocol definitions and registers them at import time.
 * This ensures the protocol registry is populated when the Next.js
 * server starts (via the plugin import chain).
 *
 * Registered protocols: aave, ajna, compound, cowswap, morpho, pendle, safe, sky, uniswap, weth
 */

import {
  protocolToPlugin,
  registerProtocol,
} from "@/keeperhub/lib/protocol-registry";
import { registerIntegration } from "@/plugins/registry";

import aaveDef from "./aave-v3";
import ajnaDef from "./ajna";
import compoundDef from "./compound";
import cowswapDef from "./cowswap";
import morphoDef from "./morpho";
import pendleDef from "./pendle";
import safeDef from "./safe";
import skyDef from "./sky";
import uniswapDef from "./uniswap";
import wethDef from "./weth";

registerProtocol(aaveDef);
registerIntegration(protocolToPlugin(aaveDef));
registerProtocol(ajnaDef);
registerIntegration(protocolToPlugin(ajnaDef));
registerProtocol(compoundDef);
registerIntegration(protocolToPlugin(compoundDef));
registerProtocol(cowswapDef);
registerIntegration(protocolToPlugin(cowswapDef));
registerProtocol(morphoDef);
registerIntegration(protocolToPlugin(morphoDef));
registerProtocol(pendleDef);
registerIntegration(protocolToPlugin(pendleDef));
registerProtocol(safeDef);
registerIntegration(protocolToPlugin(safeDef));
registerProtocol(skyDef);
registerIntegration(protocolToPlugin(skyDef));
registerProtocol(uniswapDef);
registerIntegration(protocolToPlugin(uniswapDef));
registerProtocol(wethDef);
registerIntegration(protocolToPlugin(wethDef));
